---
- name: Set CNI plugins version and architecture
  set_fact:
    cni_version: "1.4.0"
    cni_arch: "amd64"
    cni_os: "linux"

- name: Create temporary directory for CNI plugins download
  tempfile:
    state: directory
    suffix: cni-plugins
  register: cni_temp_dir

- name: Download CNI plugins archive
  get_url:
    url: "https://github.com/containernetworking/plugins/releases/download/v{{ cni_version }}/cni-plugins-{{ cni_os }}-{{ cni_arch }}-v{{ cni_version }}.tgz"
    dest: "{{ cni_temp_dir.path }}/cni-plugins-{{ cni_os }}-{{ cni_arch }}-v{{ cni_version }}.tgz"
    mode: '0644'

- name: Create CNI bin directory
  file:
    path: /opt/cni/bin
    state: directory
    mode: '0755'

- name: Extract CNI plugins to /opt/cni/bin
  unarchive:
    src: "{{ cni_temp_dir.path }}/cni-plugins-{{ cni_os }}-{{ cni_arch }}-v{{ cni_version }}.tgz"
    dest: /opt/cni/bin
    remote_src: yes
    creates: /opt/cni/bin/bridge

- name: Clean up temporary directory
  file:
    path: "{{ cni_temp_dir.path }}"
    state: absent

