---
- name: Import containerd installation and configuration tasks
  import_tasks: containerd.yaml

- name: Import runc installation tasks
  import_tasks: runc.yaml

- name: Import CNI plugins installation tasks
  import_tasks: cni-plugins.yaml

- name: Import customize containerd configuration tasks
  import_tasks: customize-containerd.yaml

