---
- name: Initialize Kubernetes cluster with kubeadm
  command: kubeadm init --ignore-preflight-errors="NumCPU,Mem"
  become: yes
  args:
    creates: /etc/kubernetes/admin.conf
  register: kubeadm_init_result

- name: Display kubeadm init output
  debug:
    var: kubeadm_init_result.stdout_lines

