---
- name: Get control plane public IP from EC2 metadata
  shell: curl -s http://169.254.169.254/latest/meta-data/public-ipv4
  register: control_plane_public_ip
  changed_when: false

- name: Get control plane private IP from EC2 metadata
  shell: curl -s http://169.254.169.254/latest/meta-data/local-ipv4
  register: control_plane_private_ip
  changed_when: false

- name: Initialize Kubernetes cluster with kubeadm
  command: >
    kubeadm init
    --ignore-preflight-errors="NumCPU,Mem"
    --apiserver-advertise-address={{ control_plane_private_ip.stdout }}
    --apiserver-cert-extra-sans={{ control_plane_public_ip.stdout }}
  become: yes
  args:
    creates: /etc/kubernetes/admin.conf
  register: kubeadm_init_result
  when: control_plane_public_ip.stdout != ""

- name: Display kubeadm init output
  debug:
    var: kubeadm_init_result.stdout_lines

- name: Set default user for kubectl config
  set_fact:
    kube_user: "ubuntu"

- name: Get user home directory
  shell: echo ~{{ kube_user }}
  register: user_home_result
  changed_when: false

- name: Display user home directory result
  debug:
    var: user_home_result

- name: Create .kube directory in user home
  file:
    path: "{{ user_home_result.stdout }}/.kube"
    state: directory
    mode: '0755'
    owner: "{{ kube_user }}"
    group: "{{ kube_user }}"
  become: yes

- name: Copy Kubernetes admin config to user .kube directory
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ user_home_result.stdout }}/.kube/config"
    remote_src: yes
    owner: "{{ kube_user }}"
    group: "{{ kube_user }}"
    mode: '0600'
  become: yes
