---
- name: Initialize Kubernetes cluster with kubeadm
  command: kubeadm init --ignore-preflight-errors="NumCPU,Mem" # TODO: remove NumCPU,Mem
  become: yes
  args:
    creates: /etc/kubernetes/admin.conf
  register: kubeadm_init_result

- name: Display kubeadm init output
  debug:
    var: kubeadm_init_result.stdout_lines

- name: Set default user for kubectl config
  set_fact:
    kube_user: "ubuntu"

- name: Get user home directory
  shell: echo ~{{ kube_user }}
  register: user_home_result
  changed_when: false

- name: Display user home directory result
  debug:
    var: user_home_result

- name: Create .kube directory in user home
  file:
    path: "{{ user_home_result.stdout }}/.kube"
    state: directory
    mode: '0755'
    owner: "{{ kube_user }}"
    group: "{{ kube_user }}"
  become: yes

- name: Copy Kubernetes admin config to user .kube directory
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ user_home_result.stdout }}/.kube/config"
    remote_src: yes
    owner: "{{ kube_user }}"
    group: "{{ kube_user }}"
    mode: '0600'
  become: yes

- name: Get control plane public IP from EC2 metadata
  shell: curl -s http://169.254.169.254/latest/meta-data/public-ipv4
  register: control_plane_public_ip
  changed_when: false

- name: Update kubeconfig to use public IP for external access
  shell: |
    export KUBECONFIG={{ user_home_result.stdout }}/.kube/config
    kubectl config set-cluster kubernetes \
      --server=https://{{ control_plane_public_ip.stdout }}:6443
  become: yes
  become_user: "{{ kube_user }}"
  when: control_plane_public_ip.stdout != ""
