kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
    - containerPort: 80
      hostPort: 8000
      protocol: TCP
    - containerPort: 443
      hostPort: 9000
      protocol: TCP
  - role: worker
    extraPortMappings:
    - containerPort: 80
      hostPort: 8001
      protocol: TCP
    - containerPort: 443
      hostPort: 9001
      protocol: TCP
  - role: worker
    extraPortMappings:
    - containerPort: 80
      hostPort: 8002
      protocol: TCP
    - containerPort: 443
      hostPort: 9002
      protocol: TCP
