apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-config
  namespace: chat-app
data:
  NOTIFICATION_SERVICE_URL: "http://real-time-ntfn-service"
  SUM_SERVICE_URL: "http://sum-service"
  MUL_SERVICE_URL: "http://mul-service"
