apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chat-ingress
  namespace: chat-app
spec:
  ingressClassName: nginx
  rules:
  # Comment out host to allow access via IP address
  # When you have a domain, uncomment and set: host: yourdomain.com
  # - host: chat.local
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: message-service
            port:
              number: 80
      - path: /events
        pathType: Prefix
        backend:
          service:
            name: real-time-ntfn-service
            port:
              number: 80
      - path: /notify
        pathType: Prefix
        backend:
          service:
            name: real-time-ntfn-service
            port:
              number: 80
      - path: /sum
        pathType: Prefix
        backend:
          service:
            name: sum-service
            port:
              number: 80
      - path: /mul
        pathType: Prefix
        backend:
          service:
            name: mul-service
            port:
              number: 80
      - path: /sub
        pathType: Prefix
        backend:
          service:
            name: sub-service
            port:
              number: 80
      - path: /calc
        pathType: Prefix
        backend:
          service:
            name: calc-service
            port:
              number: 80
