apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chat-ingress
  namespace: chat-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: chat.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: message-service
            port:
              number: 80
      - path: /events
        pathType: Prefix
        backend:
          service:
            name: real-time-ntfn-service
            port:
              number: 80
      - path: /notify
        pathType: Prefix
        backend:
          service:
            name: real-time-ntfn-service
            port:
              number: 80

