apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: chat-app

resources:
  - namespace.yaml
  - configmap.yaml
  - message/
  - real-time-ntfn/
  - sum/
  - mul/
  - ingress.yaml  #  requires installed ingress controller
